some-one:
  #Reiting отвечает за социальный рейтинг
  Reiting: 30
  #ProfilStatus - это статус профиля(открыт ли он)
  ProfilStatus: close
  #About - информация, которую указал игрок в поле о себе
  About: да
  #Age - информация об игроке, которую он указал в поле возраст
  Age: '1'
  #PlayerCels - цели игрока
  PlayerCels: нет
  #Nick - ник игрока(не майнкрафте)
  Nick: глэк
  #RealName - это информация об игроке, которую он указал в поле Реальное Имя
  RealName: Абоба, глэк
  #DiscordName - дискорд ник этого игрока
  DiscordName: глек
  #LorePlayer - лор игрока
  LorePlayer: ээээээ....
  #Status - статус игрока на сервере
  Status: глэк